### ISSUE TITLE
Sometimes dns_get_record() takes too long to respond

### ISSUE THREAD

**Issue by vaidas-lungis** [hostinger/disposable-emails#21]
This php function does not have a timeout option.

http://stackoverflow.com/questions/14065946/what-would-cause-checkdnsrr-or-dns-get-record-to-take-too-long

A possible solution is to create a wrapper.
Like 
```php
function dig_get_dns_record($type, $host) 
{ 
    $cleaned_host = escapeshellcmd($host);
    ob_start(); 
        // Note: for this to work on Windows/XAMPP "dig" has to be installed and the search path
        passthru("dig $type $cleaned_host"); 
        $lookup = ob_get_contents(); 
    ob_end_clean(); 
    //echo "<pre>" . $lookup . "</pre>";  // Remove comment to see dig output
    return $lookup; 
}   
```
or 
>You have to write your own function that will build a UDP packet to query a DNS server, call the socket_set_timeout() function to set a timeout value, send the UDP packet, and hope that you get a response.

also related
https://www.reddit.com/r/PHP/comments/2k3ns7/dns_get_record_suddenly_running_very_slowly/

**Comment by fordnox** [comment]
also a solution for linux and if exec is allowed on server:

```php

CheckMX("fakedomain.org");
CheckMX("hotmail.com");

function CheckMX($domain) {
        exec("dig +short MX " . escapeshellarg($domain),$ips);
        if($ips[0] == "") {
                print "MX record found for $domain not found!\n";
                return FALSE;
        }
        print "MX Record for $domain found\n";
        return TRUE;
}

```

**Comment by tonyspa** [comment]
You should return  from`dig` solution same results (array) as `dns_get_record();`
